---
title: MonetDB
logo: "/logos/monetdblarge.png"
dplyr: "Yes"
driver: "No"
package: MonetDBLite
aliases:
  - /monetdb
---

MonetDBLite for R is a SQL database that runs inside the R environment for statistical computing and does not require the installation of any external software. MonetDBLite is based on free and open-source [MonetDB](https://www.monetdb.org/Home), a product of the [Centrum Wiskunde & Informatica](http://www.cwi.nl/).

MonetDBLite is similar in functionality to RSQLite, but typically completes queries blazingly fast due to its columnar storage architecture and bulk query processing model. Since both of these embedded SQL options rely on the the R DBI interface, the conversion of legacy RSQLite project syntax over to MonetDBLite code should be a cinch.


## Installation

You can install the latest released version of MonetDBLite from CRAN with:

``` r
install.packages("MonetDBLite")
```

The latest development version from GitHub on the command line:

```
git clone https://github.com/hannesmuehleisen/MonetDBLite-R.git --depth 1 --recursive
R CMD INSTALL MonetDBLite-R
```

## Usage

For information on how to use, and to report bugs, please refer to the package's official GitHub repo: https://github.com/hannesmuehleisen/MonetDBLite-R

