---
title: Cassandra
logo: "/logos/cassandralarge.png"
dplyr: "No"
driver: "Yes"
---

## Driver Options

- **RStudio Professional Drivers** - RStudio Workbench (formerly RStudio Server Pro), RStudio Desktop Pro, RStudio Connect, or Shiny Server Pro users can download and use RStudio Professional Drivers at no additional charge. These drivers include an ODBC connector for Apache Impala.  RStudio delivers standards-based, supported, professional ODBC drivers. Use RStudio Professional Drivers when you run R or Shiny with your production systems. See the [RStudio Professional Drivers](https://www.rstudio.com/products/drivers/) for more information. 

## Package Options

The **`odbc`** package, in combination with a driver, provides `DBI` support and an ODBC connection.

## Connection Settings

There are settings needed to make a connection:

  - **Driver** - See the [Drivers](/drivers) section for setup information 
  - **Host** - A network path to the database server
  - **Port** - Should be set to **9042**
  - **Keyspace** - Data replication namespace (not required)
  - **AuthMec** - Use 0 for no authentication, and 1 for user name/password
  - **UID** - The user's network ID or server local account
  - **PWD** - The account's password

```{r,eval=FALSE}
con <- DBI::dbConnect(odbc::odbc(),
                      Driver   = "[your driver's name]",
                      Host     = "[your server's path or name]",
                      Port     = 9042,
                      Keyspace = "[your keypace's name]",
                      AuthMech = 1,
                      UID      = rstudioapi::askForPassword("Database user"),
                      PWD      = rstudioapi::askForPassword("Database password")
                      )
```



